### ISSUE TITLE
textlint-rule-*をロードするIFが欲しい

### ISSUE THREAD

**Issue by 1000ch** [azu/textlint#19]
Atomのプラグインを作りたいときに、Atomで開かれているディレクトリの`node_modules/textlint-rule-*`をtextlintにロードしてあげると、そのプロジェクトの`package.json`と`.textlintrc`に依存関係を完結させることが出来そうなので・・・。

つまり、
https://github.com/azu/textlint/blob/master/lib/textlint-engine.js#L65-L80
あたりをTextLintEngineのインスタンスから実行したいです。

https://github.com/1000ch/linter-textlint/blob/master/index.js#L20-L26

**Comment by azu** [comment]
@1000ch こんな感じでどうでしょうか?
https://github.com/azu/textlint/pull/20

`TextLintEngine#loadRule` というのを追加しました。

**Comment by 1000ch** [comment]
@azu ありがとうございます。が、説明不足でした:bow:

`tryResolve()`だとNodeの実行パス（`/Applications/Atom.app/Contents/Resources/app.asar/static`?）からモジュール辿ると思うので、Atomで開いているプロジェクトのパス（例えば`~/example-project`）にインストールされてる`~/example-project/node_modules/textlint-rule-max-ten`は参照できないかもです。

`TextLintEngine.prototype.loadRule`の第二引数あたりにパスのコンテキストを渡せるようにして、渡された場合は、それ含めて`tryResolve`してもらえると良いかもしれません。こちらとしては、ですが。

**Comment by azu** [comment]
@1000ch 追加したものを[3.4.0](https://github.com/azu/textlint/releases/tag/3.4.0 "3.4.0")としてリリースしました

**Comment by 1000ch** [comment]
@azu Wikiのプラグイン達が期待通りに動くようになりました :+1:
